# Generated by Django 5.2.1 on 2025-06-22 06:00

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('contact_info', models.TextField(verbose_name="Aloqa ma'lumotlari")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'db_table': 'Mijoz',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=0.5, size=[800, 800], upload_to='raw_materials/images/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Hom-ashyolar',
                'verbose_name_plural': 'Hom-ashyolar',
                'db_table': 'Hom-ashyolar',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('role', models.CharField(choices=[('Mix ustasi', 'Mix ustasi'), ("Yog'och ustasi", "Yog'och ustasi"), ('Sintafon ustasi', 'Sintafon ustasi')], max_length=50, verbose_name="Ro'li")),
                ('tasks', models.TextField(verbose_name='Vazifalar')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'db_table': 'Ishchi',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('information', models.TextField(verbose_name="Ma'lumot")),
                ('type', models.CharField(max_length=100, verbose_name='Turi')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=0.5, size=[800, 800], upload_to='orders/images/', verbose_name='Rasmi')),
                ('status', models.CharField(choices=[('New', 'Yangi'), ('In Progress', 'Tayyorlanmoqda'), ('Ready', 'Tayyor')], default='New', max_length=50, verbose_name='Holati')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='common.customer', verbose_name='Buyurtmachi')),
                ('raw_materials', models.ManyToManyField(related_name='orders', to='common.rawmaterial', verbose_name='Hom-ashyo')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
                'db_table': 'Zakaz',
            },
        ),
        migrations.CreateModel(
            name='OrderWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Vazifasi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.order')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.worker')),
            ],
            options={
                'verbose_name': 'Zakaz-Ishchi',
                'verbose_name_plural': 'Zakaz-Ishchilar',
                'db_table': 'ZakazIshchilar',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='workers',
            field=models.ManyToManyField(related_name='orders', through='common.OrderWorker', to='common.worker', verbose_name='Ishchilar'),
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=85, scale=0.5, size=[800, 800], upload_to='products/images/', verbose_name='Rasmi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_product', to='common.order')),
                ('workers', models.ManyToManyField(related_name='finished_products', to='common.worker', verbose_name='Ishchilar')),
            ],
            options={
                'verbose_name': 'Tayyor-Mahsulot',
                'verbose_name_plural': 'Tayyor-Mahsulotlar',
                'db_table': 'Tayyor-Mahsulot',
            },
        ),
    ]
